sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: raw

    tables:
      - name: g01
      - name: g02
      - name: lga_code
      - name: lga_suburb
      - name: listings